export { default as Home } from "./Home.js";
export { default as Login } from "./Login.js";
export { default as Routine } from "./Routines.js";
export { default as Activities } from "./Activities.js";
export { default as MyRoutines } from "./MyRoutines.js";
export { default as Signup } from "./Signup.js";
export { default as CreateRoutine } from "./CreateRoutine.js";
export { default as CreateActivities } from "./CreateActivities.js";
export { default as Send_a_message } from "./Send_a_message.js";
